spring:
  application:
    name: user

server:
  port: 8888

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8099,localhost:8199,localhost:8299
    ServerListRefreshInterval: 5000